# Generated by Django 5.0.1 on 2025-07-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='teacher',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='study_materials/banners/'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='study_materials/zips/'),
        ),
    ]
