# Generated by Django 5.0.1 on 2025-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_purchase_status_purchase_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='subject',
            new_name='expertise',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profile_photo/photos/'),
        ),
    ]
